name: Performance Analysis Experiments
run-name: "Experiment '${{ inputs.experiment }}' by @${{ github.actor }}"
on:
  workflow_dispatch:
    inputs:
      experiment:
        description: 'The name of the experiment to run'
        required: true
        type: choice
        options:
        - tsnode
      warmups:
        description: 'The number of warmup runs'
        required: true
        type: string
        default: "3"
      samples:
        description: 'The number of samples collected'
        required: true
        type: string
        default: "20"
      groups:
        description: "The groups to include in this experiment, comma separated."
        required: true
        type: string
        default: "control,experimental"
      data:
        description: "The file path for the captured data."
        default: "experimental-data.json"
        type: string
        required: true

env:
  HYPERFINE_VERSION: v1.16.1

jobs:
  run-experiment:
    name: "Experiment '${{ inputs.experiment }}' by @${{ github.actor }}"
    runs-on: ubuntu-latest
    steps:
    - name: "Install Hyperfine"
      run: wget https://github.com/sharkdp/hyperfine/releases/download/${{ env.HYPERFINE_VERSION }}/hyperfine_1.16.1_amd64.deb && sudo dpkg -i hyperfine_1.16.1_amd64.deb
    - name: "Download Pulumi Source"
      uses: actions/checkout@v3
      with:
        path: "${{ github.workspace }}/pulumi"
        repository: 'pulumi/pulumi'
    - name: "Checkout Repo Code"
      uses: actions/checkout@v3
      with:
        path: "${{ github.workspace }}/experiments"
    - name: "Setup Go"
      uses: "actions/setup-go@v3"
    - name: "Setup Node"
      uses: "actions/setup-node@v3"
      with:
        node-version: 16
        cache: "yarn"
        cache-dependency-path: "pulumi/sdk/nodejs/yarn.lock"
    - name: "Run Experiment"
      run: ./scripts/ci.bash
      working-directory: "${{ github.workspace }}/experiments"
      env:
        WARMUP_RUNS: ${{ inputs.warmups }}
        SAMPLES: ${{ inputs.samples }}
        EXPERIMENT: ${{ inputs.experiment }}
        GROUPS: ${{ inputs.groups }}
        DATA_FILE: ${{ inputs.data }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PULUMI_SRC: "${{ github.workspace }}/experiments/pulumi" # location of the source code.
    - name: "Upload Artifacts"
      uses: actions/upload-artifact@v3
      with:
          name: ${{ inputs.data }}
          path: "${{ github.workspace }}/experiments/${ inputs.data }}"
          retention-days: 14